name = "ConstrainedSimplexSearch"
uuid = "18a5e75d-c893-44ea-8c57-0eddfae82f21"
authors = ["Clpr <zhao1tian1hao1@outlook.com>"]
version = "0.2.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[weakdeps]
Optim = "429524aa-4258-5aef-a3af-852621145aeb"

[extensions]
ConstrainedSimplexSearchOptimExt = "Optim"

[compat]
LinearAlgebra = "1.12"
Optim = "1, 2"
Printf = "1.11, 1.12"
julia = "1.12"

[extras]
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Optim", "Test"]
